services:
  - type: web
    name: conversational-ai
    dockerfile: Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1